---
- hosts: localhost
  become: true
  
  tasks:

    - name: Create Zabbix directory in opt
      ansible.builtin.file:
        path: /opt/temp/Zabbix
        state: directory
        mode: '0755'

    - name: Download Zabbix rpm
      ansible.builtin.get_url:
        url: https://repo.zabbix.com/zabbix/6.2/rhel/7/x86_64/zabbix-release-6.2-3.el7.noarch.rpm
        dest: /opt/temp/Zabbix
        mode: '0744'

    - name: Install Zabbix Repo
      ansible.builtin.yum:
        name: /opt/temp/Zabbix/zabbix-release-6.2-3.el7.noarch.rpm
        state: present

    - name: Install zabbix-agent2
      yum:
        name: zabbix-agent2
        state: present

    - name: Install zabbix-agent2-plugins
      yum:
        name: zabbix-agent2-plugin-*
        state: present

    - name: Copy zabbix configuration file
      ansible.builtin.copy:
        src: <insert source location here>
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: root
        group: root
        mode: '0644'

    - name: Ensure zabbix-agent2 is installed
      yum:
        name: zabbix-agent2
        state: present

    - service:
        name: zabbix-agent2
        state: restarted

    - name: Ensure zabbix-agent2 is started and enabled
      service:
        name: zabbix-agent2
        state: started
        enabled: yes