---

#zabbix-agent2 and zabbix-agent will not work together simultaneously. Detecting if zabbix-agent exists, and if so disabling zabbix-agent
- name: Ensure zabbix-agent is stopped and disabled
  service:
    name: zabbix-agent
    state: stopped
    enabled: no
  ignore_errors: true

- name: Import Zabbix GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591

- name: Install Zabbix repo
  ansible.builtin.command: rpm -Uvh https://repo.zabbix.com/zabbix/6.2/rhel/7/x86_64/zabbix-release-6.2-3.el7.noarch.rpm
  ignore_errors: true

- name: Clean yum cache
  ansible.builtin.command: yum clean all

- name: Install zabbix-agent
  yum:
    name: zabbix-agent
    state: present

- name: Install zabbix-agent2
  yum:
    name: zabbix-agent2
    state: present

- name: Install zabbix-agent2-plugins
  yum:
    name: zabbix-agent2-plugin-*
    state: present

- name: Config zabbix_agent2.conf Server
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    search_string: 'Server=127.0.0.1'
    line: "{{ server }}"
    owner: root
    group: root

- name: Config zabbix_agent2.conf ServerActive
  ansible.builtin.lineinfile:
    path: /etc/zabbix/zabbix_agent2.conf
    search_string: 'ServerActive=127.0.0.1'
    line: "{{ serveractive }}"
    owner: root
    group: root

- name: Ensure zabbix-agent2 is installed
  yum:
    name: zabbix-agent2
    state: present

- name: Ensure zabbix-agent2 is started and enabled
  service:
    name: zabbix-agent2
    state: started
    enabled: yes